---
title: "REM"
output: 
  pdf_document:
    
    toc: false
    toc_depth: 4
    number_sections: false
    fig_caption: true
    keep_tex: true
    latex_engine: xelatex
editor_options:
y  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}

rm(list=ls())
setwd("~/RProjects/SNA_REM/REM_new/")
library(tidyr)
library(caret)
library(network)
library(relevent)
library(kableExtra)
library(survival)
library(rem)
library(dplyr)
library(ggplot2)
library(igraph)
library(ggraph)
library(RColorBrewer)
library(tidyr)
knitr::opts_chunk$set(fig.align='center', fig.width=8, fig.height=6, options(tidy = TRUE), tidy.opts = list(width.cutoff = 60))

```

## Interactions and Actors Data

Interactions between the team members for high-performance sessions:

-   sender

-   receiver

-   time of the interaction

-   type of interaction (dialogue act type)

Actors Data:

-   name

-   gender
```{r}
all_interactions <- readRDS("data/all_sessions.RDS") %>% 
  select(session, sender_id,sender, sender_gender, receiver_id, receiver, receiver_gender, dialog, time, performance) %>% mutate(sender_gender = as.factor(sender_gender), receiver_gender = as.factor(receiver_gender), time = as.numeric(time)) %>% na.omit()

unique(all_interactions$session)
# remove  2103 2104
all_interactions <- all_interactions %>% filter(session != 2103 & session != 2104)


# filter into hgih anda low respectively
high_perf_interactions <- all_interactions %>% filter(performance == "high")
low_perf_interactions <- all_interactions %>% filter(performance == "low")
dim(high_perf_interactions)
dim(low_perf_interactions)

#saveRDS(high_perf_interactions, "data/high_performance_sessions0505.RDS")
#saveRDS(low_perf_interactions, "data/low_performance_sessions0505.RDS")
```


```{r}
# Interactions Data Frame (Edges)


data.frame(unique(high_perf_interactions$sender_id), 
           unique(high_perf_interactions$sender)) %>% rename(id = "unique.high_perf_interactions.sender_id.", name = "unique.high_perf_interactions.sender.") %>% 
  mutate(gender = c("female", "male","female","male", "male")) %>% mutate(gender = as.factor(gender)) %>% arrange(id) -> actors_attributes_final


# filter high performance sessions
high_perf_interactions %>% filter(session != 2103 & session != 2104) %>%  filter(sender_id %in% actors_attributes_final$id) %>% filter(receiver_id %in% actors_attributes_final$id) %>% select(-session) %>% select(sender_id, receiver_id,everything()) %>% 
  mutate(time = time - min(time)) -> high_perf_interactions



low_perf_interactions %>% filter(sender_id %in% actors_attributes_final$id) %>% filter(receiver_id %in% actors_attributes_final$id) %>% select(sender_id, receiver_id, everything()) %>%  select(-session) %>%
  mutate(time = time - min(time)) -> low_perf_interactions

dim(high_perf_interactions)

dim(low_perf_interactions)
```

```{r}
# kable print
actors_attributes_final %>% arrange(id) %>% kable("html") %>% kable_styling("striped", full_width = F) 
```




```{r}
actors_attributes <- actors_attributes_final
interactions <- high_perf_interactions
g.h <- graph_from_data_frame(high_perf_interactions, directed = TRUE)
V(g.h)$name <- actors_attributes_final$name
V(g.h)$gender <- actors_attributes_final$gender
E(g.h)$dialog <- interactions$dialog
E(g.h)$time <- interactions$time
```


```{r}
par(mfrow=c(1,1), mar=c(1,1,1,1))
palette <- brewer.pal(8, "Pastel2") 
pal2 <- brewer.pal(8, "Set3")
plot(g.h, edge.color = dialog_col[E(g.h)$dialog], edge.width = .8, vertex.color = gender_col[V(g.h)$gender], vertex.size = 25, vertex.label.cex = 0.8, vertex.label.color = "black", edge.arrow.size = 0.5, edge.curved = 0.1, main = "high-performing sessions", cex.main = .1, cex.sub = 0.8)
legend("topleft", legend = c("Backchannel", "Disruption", "Floor-Grabber", "Question", "Statement"), fill = dialog_col, title = "Dialogue Type", cex = 0.8)
```

```{r}
interactions <- low_perf_interactions
g.l <- graph_from_data_frame(low_perf_interactions, directed = TRUE)
V(g.l)$name <- actors_attributes_final$name
V(g.l)$gender <- actors_attributes_final$gender
E(g.l)$dialog <- interactions$dialog
E(g.l)$time <- interactions$time
```


```{r}
par(mfrow=c(1,1), mar=c(2,2,2,2))
palette <- brewer.pal(8, "Pastel2") 
pal2 <- brewer.pal(8, "Set3")
plot(g.l, edge.color = dialog_col[E(g.l)$dialog], edge.width = .8, vertex.color = gender_col[V(g.l)$gender], vertex.size = 25, vertex.label.cex = 0.8, vertex.label.color = "black", edge.arrow.size = 0.5, edge.curved = 0.1, main = "low-performing sessions", cex = .5)
```

```{r}
interactions <- high_perf_interactions

now <- Sys.time()
REM.data.high.0505 <- createRemDataset(
  data = high_perf_interactions, 
  sender = interactions$sender_id,
  target = interactions$receiver_id,
  eventSequence = interactions$time,
  eventAttribute = interactions$dialog,
  atEventTimesOnly = TRUE, 
  untilEventOccurrs = TRUE,
  includeAllPossibleEvents = FALSE, 
  returnInputData = FALSE
)


comp_time <- Sys.time() 
cat("Time taken to create REM dataset for high performance sessions: ", comp_time - now, "\n")


#save as RDS
saveRDS(REM.data.high.0505, "data/RemDatasetLow.RDS")

```

```{r, eval=TRUE}
interactions <- low_perf_interactions
now <- Sys.time()
REM.data.low.0505 <- createRemDataset(
  data = low_perf_interactions, 
  sender = interactions$sender_id,
  target = interactions$receiver_id,
  eventSequence = interactions$time,
  eventAttribute = interactions$dialog,
  atEventTimesOnly = TRUE, 
  untilEventOccurrs = TRUE,
  includeAllPossibleEvents = FALSE, 
  returnInputData = FALSE
)

# end time
comp_time <- Sys.time() 
cat("Time taken to create REM dataset for low performance sessions: ", comp_time - now, "\n")

#save as RDS'
saveRDS(REM.data.low.0505, "data/RemDatasetLow.RDS")
```




```{r}
#high performance

surv_object <- Surv(time = REM.data.high.0505$eventTime, event = REM.data.high.0505$eventDummy)
REM.data <- REM.data.high.0505

# save high surv_object
#saveRDS(surv_object, "data/surv_object_high.RDS")
#saveRDS(REM.data, "data/REM_data_high.RDS")
```


```{r}
high_perf_collab <- readRDS("data/surv_object_high.RDS")
REM.data <- readRDS("data/REM_data_high.RDS")

# base model
base_model0 <- coxph(high_perf_collab ~ 1, data = REM.data)
print(summary(base_model0))

# sender model
model1 <- coxph(high_perf_collab ~ sender + 1, data = REM.data)
print(summary(model1))

# receiver model
model2 <- coxph(high_perf_collab ~ target + 1, data = REM.data)
print(summary(model2))
# sender - receiver model
model3 <- coxph(high_perf_collab ~ sender + target + 1, data = REM.data)
print(summary(model3))


# dialogue act model
model4 <- coxph(high_perf_collab ~ eventAttribute + 1, data = REM.data)
print(summary(model4))

# sender and dialogue act model
model5 <- coxph(high_perf_collab ~ sender + eventAttribute, data = REM.data)
print(summary(model5))

# combined model
model6 <- coxph(high_perf_collab ~ sender * eventAttribute, data = REM.data)
print(summary(model6))

# format print all model results
for (model in list(base_model0, model1, model2, model3, model4, model5, model6)) {
  # format print all model for comaprison
  print(summary(model))
}

high_summary <- NULL
for (model in list(model1, model2, model3, model4, model5, model6)) {
  summary <- summary(model)
  add <- data.frame(
    Model = (summary(model)[1]) %>% as.character(),
    Concordance = summary$concordance[1],
    LogRankTest = summary$logtest[1],
    WaldTest = summary$waldtest[1],
    ScoreTest = summary$sctest[1]
  )
  high_summary <- rbind(high_summary, add)
  }

# save models
saveRDS(high_summary, "data/high_summary.RDS")
```

```{r}
# save model outputs tphgther
#saveRDS(list(base_model0, model1, model2, model3, model4, model5, model6), "data/high_perf_models.RDS")
```

```{r}
#high performance

#surv_object_low <- Surv(time = REM.data.low.0505$eventTime, event = REM.data.low.0505$eventDummy)
#REM.data <- REM.data.low.0505


# save high surv_object
#saveRDS(surv_object_low, "data/surv_object_low.RDS")
#saveRDS(REM.data, "data/REM_data_low.RDS")
```


```{r}
low_perf_collab <- readRDS("data/surv_object_low.RDS")
REM.data <- readRDS("data/REM_data_low.RDS")

# base model
base_model0 <- coxph(low_perf_collab ~ 1, data = REM.data)
print(summary(base_model0))

# sender model
model1 <- coxph(low_perf_collab ~ sender + 1, data = REM.data)
print(summary(model1))

# receiver model
model2 <- coxph(low_perf_collab ~ target + 1, data = REM.data)
print(summary(model2))
# sender - receiver model
model3 <- coxph(low_perf_collab ~ sender + target + 1, data = REM.data)
print(summary(model3))


# dialogue act model
model4 <- coxph(low_perf_collab ~ eventAttribute + 1, data = REM.data)
print(summary(model4))

# sender and dialogue act model
model5 <- coxph(low_perf_collab ~ sender + eventAttribute, data = REM.data)
print(summary(model5))

# combined model
model6 <- coxph(low_perf_collab ~ sender * eventAttribute, data = REM.data)
print(summary(model6))

# format print all model results
for (model in list(base_model0, model1, model2, model3, model4, model5, model6)) {
  # format print all model for comaprison
  print(summary(model))
}

low_summary <- NULL
for (model in list(model1, model2, model3, model4, model5, model6)) {
  summary <- summary(model)
  add <- data.frame(
    Model = (summary(model)[1]) %>% as.character(),
    Concordance = summary$concordance[1],
    LogRankTest = summary$logtest[1],
    WaldTest = summary$waldtest[1],
    ScoreTest = summary$sctest[1]
  )
  low_summary <- rbind(low_summary, add)
  
  }
# save model outputs tphgther
saveRDS(list(base_model0, model1, model2, model3, model4, model5, model6), "data/low_perf_models.RDS")
```


```{r}

cbind(high_summary, low_summary) %>% as.data.frame() -> summary_table

# print table in nice format
summary_table %>% kable("html") %>% kable_styling("striped", full_width = F) 
```


```{r}
# code to fetch and comapre lwo and high for each ondel and print one by one

low_models <- readRDS("data/low_perf_models.RDS")
high_models <- readRDS("data/high_perf_models.RDS")

# highlight model in yellow
for (i in 1:length(low_models)) {
  cat("\n############ \t Model ", i-1, "\t ############\n")
  cat("----------- Low -----------\n")
  print(summary(low_models[[i]]))
  cat("----------- High -----------\n")
  print(summary(high_models[[i]]))
}

```


