---
title: "REM"
output: 
  pdf_document:
    
    toc: false
    toc_depth: 4
    number_sections: false
    fig_caption: true
    keep_tex: true
    latex_engine: xelatex
editor_options:
y  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}

rm(list=ls())

library(caret)
library(network)
library(relevent)
library(survival)
library(rem)
library(dplyr)
library(ggplot2)
library(igraph)
library(ggraph)
library(RColorBrewer)
library(tidyr)
setwd("~/RProjects/SNA_REM/REM_new")
knitr::opts_chunk$set(fig.align='center', fig.width=8, fig.height=6, options(tidy = TRUE), tidy.opts = list(width.cutoff = 60))

```


```{r}
# Interactions Data Frame (Edges)
high_perf_interactions <- readRDS("data/high_performance_sessions.RData") %>% 
  select(session, sender_id, receiver_id, dialog, time)


interactions <- high_perf_interactions %>%
  mutate(
    sender_id = as.integer(sender_id),  
    receiver_id = as.integer(receiver_id), 
    dialog = as.factor(dialog) 
  )



actors_attributes <- data.frame(
  id = 1:8,
  name = c("Igor", "Ashley", "Will", "Katya", "Saleh", "Oleg", "Vika", "Alex"),
  gender = c("male", "female", "male", "female", "male", "male", "female", "male")
)

# Create dummy variables for gender
dummyvars <- dummyVars(" ~ gender", data = actors_attributes)
actors_attributes <- cbind(actors_attributes, predict(dummyvars, actors_attributes)) %>%
  select(id, name, gendermale)
```



```{r}
exclude_session <- 2103

high_perf_interactions %>% filter(receiver_id != 0) %>% group_by(session) %>% filter(session != exclude_session) %>% ungroup() %>% select(-session) %>% mutate(time = 1:nrow(.))  %>% select(sender_id, receiver_id, time,dialog)  %>% mutate(dialog = as.factor(dialog), sender_id = as.integer(sender_id), receiver_id = as.integer(receiver_id)) -> interactions

dim(interactions)
```


```{r}
head(interactions)
```


```{r}
actors_attributes %>% filter(id %in% interactions$sender_id) %>% filter(id %in% interactions$receiver_id) -> actors_attributes
head(actors_attributes)


g_subset <- graph_from_data_frame(interactions, directed = TRUE, vertices = data.frame(actors_attributes))


V(g_subset)$gender <- actors_attributes$gender[match(V(g_subset)$name, actors_attributes$name)]
V(g_subset)$name <- actors_attributes$name[match(V(g_subset)$name, actors_attributes$name)]


dialog_colors <- RColorBrewer::brewer.pal(n = length(unique(interactions$dialog)), name = "Pastel2")
dialog_color_map <- setNames(dialog_colors, unique(interactions$dialog))


ggraph(g_subset, layout = 'fr') +
  geom_edge_link(aes(color = dialog), alpha = 0.7, edge_width = .2, lineend = "butt", arrow = arrow(type = 'closed', length = unit(4, 'mm'))) +
  scale_edge_color_manual(values = dialog_color_map) +
  geom_node_point(aes(color = factor(gender)), size = 4, alpha = 0.8) +
  geom_node_text(aes(label = name), repel = TRUE,  color = "black", size = 3, vjust = 1, nudge_x = -.02) +
  scale_color_manual(values = c('0' = 'red', '1' = 'cyan')) +
  theme_void() +
  labs(subtitle = "High Performing Session", color = "Gender", edge_color = "Dialog") +
  theme(legend.position = "right", legend.title = element_text(size = 8))
```



```{r, eval=FALSE}
interactions$time<-as.numeric(interactions$time) 


# REM.data <- createRemDataset(
#   data = interactions, 
#   sender = interactions$sender_id,
#   target = interactions$receiver_id,
#   eventSequence = interactions$time,
#   eventAttribute = interactions$dialog,
#   atEventTimesOnly = TRUE, 
#   untilEventOccurrs = TRUE,
#   includeAllPossibleEvents = FALSE, 
#   returnInputData = FALSE
# )

#save as RDS
#saveRDS(REM.data, "data/RemDatasetHigh.RDS")

```

```{r, eval=TRUE}
readRDS("data/RemDatasetHigh.RDS") -> REM.data
```



```{r}
dim(REM.data)
```

```{r}
str(REM.data)
```

```{r}
surv_object <- Surv(time = REM.data$eventTime, event = REM.data$eventDummy)
```


```{r}
base_model <- coxph(surv_object ~ 1, data = REM.data)
summary(base_model)
```



```{r}
sender_model <- coxph(surv_object ~ sender + 1, data = REM.data)


summary(sender_model)

```


```{r}
rec_model <- coxph(surv_object ~ target + 1, data = REM.data)


summary(rec_model)


```
```{r}
snd_rec_model <- coxph(surv_object ~ sender + target + 1, data = REM.data)
summary(snd_rec_model)


```

```{r}

event_model <- coxph(surv_object ~ eventAttribute + 1, data = REM.data)
summary(event_model)
```

```{r}
model4 <- coxph(surv_object ~ sender + eventAttribute, data = REM.data)
summary(model4)
```


```{r}
model5 <- coxph(surv_object ~ sender * eventAttribute, data = REM.data)
summary(model5)
```
```{r}
model6 <- coxph(surv_object ~ sender + target + eventAttribute, data = REM.data)
summary(model6)
```


