---
output:
pdf_document: default
html_document: default
---

```{r, message = FALSE, include = FALSE}
# Last Updated: 02/12
rm(list = ls())

# Load libraries
library(rstudioapi)
library(tidyverse)
library(tidyr)
library(ggplot2)
library(dplyr)

library(RColorBrewer)
library(dplyr)
library(igraph)
library(readxl)
library(igraph)
library(glmnet)
library(remsonic)
library(skimr)
library(dplyr)
library(relevent)
# Set Path
setwd("~/RProjects/SNA_REM/REM_new/")
```

# Session 2103

```{r}
# read excel
dialog_data <- read_excel("data/nek21.xlsx", sheet = "Sheet1_Dialogs")
head(dialog_data)
```

All Igor Ashley Will Katya Saleh Oleg Vika Alex 0 1 2 3 4 5 6 7 8

```{r}
people_list <- unique(dialog_data$sender)
# if the sender is All, make ID is 0
people_list <- people_list[people_list != "All"]
lookup_table <- setNames(seq_along(people_list), people_list)
# add All to the lookup table with ID 0
lookup_table <- c(All = 0, lookup_table)
print(lookup_table)
```

```{r}
dialog_data[, 'sender_id'] <- lookup_table[dialog_data$sender]
dialog_data[, 'receiver_id'] <- lookup_table[dialog_data$receiver]
head(dialog_data)
```

```{r}
perf_data <- read_excel("data/nek21.xlsx", sheet = "Sheet2_Perfs")
head(perf_data)
```

```{r}
# find all sessionsi of where perf_level is low, high, fail respectively
low_perf <- perf_data %>% filter(perf_level == "low")
high_perf <- perf_data %>% filter(perf_level == "high")
fail_perf <- perf_data %>% filter(perf_level == "failed")
print(paste("Number of low performance sessions: ", nrow(low_perf), list(low_perf$session)))
print(paste("Number of high performance sessions: ", nrow(high_perf), list(high_perf$session)))
print(paste("Number of fail performance sessions: ", nrow(fail_perf), list(fail_perf$session)))
```

```{r}
print("High performance sessions")

for (s in high_perf$session) {
  print(paste("Session: ", s))
  # for each session, add numbers 1 to the total row numbers representing the event order
  session_data <- dialog_data %>% filter(session == s)
  session_data <- session_data %>% mutate(event_order = seq(1, nrow(session_data)))
  assign(paste("df_high_", s, sep = ""), session_data)
}


print("Low performance sessions")
for (s in low_perf$session){
  print(paste("Session: ", s))
  session_data <- dialog_data %>% filter(session == s)
  session_data <- session_data %>% mutate(event_order = seq(1, nrow(session_data)))
  assign(paste("df_low_", s, sep = ""), session_data)
}

```
