---
title: "High Performance Session (2105)"
output:
pdf_document: default
html_document: default
---
```{r, message = FALSE, include = FALSE}
# Last Updated: 02/12
rm(list = ls())

# Load libraries
library(rstudioapi)
library(tidyverse)
library(tidyr)
library(ggplot2)
library(dplyr)

library(RColorBrewer)
library(dplyr)
library(igraph)
library(readxl)
library(igraph)
library(glmnet)
library(remsonic)
library(skimr)
library(dplyr)
library(relevent)
# Set Path
setwd("~/RProjects/SNA_REM/REM_new/")
```

# Session 2103
```{r}
# read excel
dialog_data <- read_excel("data/nek21.xlsx", sheet = "Sheet1_Dialogs")
head(dialog_data)
df_high2105 <- dialog_data[dialog_data$session == 2105,]
head(df_high2105)
```
```{r}

people_list <- unique(df_high2105$sender)

lookup_table <- setNames(seq_along(people_list), people_list)
print(lookup_table)

df_high2105[, 'sender_id'] <- lookup_table[df_high2105$sender]
df_high2105[, 'receiver_id'] <- lookup_table[df_high2105$receiver]
head(df_high2105)

# for event order, add 1 to make it start from 1  and icnreasing by 1 (row number)
df_high2105[, 'event_order'] <- seq(1, nrow(df_high2105))
head(df_high2105)

# convert male and female as factor
df_high2105$sender_gender <- as.factor(df_high2105$sender_gender)
df_high2105$receiver_gender <- as.factor(df_high2105$receiver_gender)
df_high2105$sender_dialog <- as.factor(df_high2105$sender_dialog)
df_high2105$receiver_dialog <- as.factor(df_high2105$receiver_dialog)
```




```{r}
# Load the data
data <- data.frame(sid = df_high2105$sender_id, rid = df_high2105$receiver_id, time = df_high2105$event_order)


# Calculate statistics for the REM
stats.intercept <- Constant(data)
stats.rrecsnd <- RRecSnd(data)
stats.rsndsnd <- RSndSnd(data)

# Combine statistics
stats1 <- combine.stats(
  '[Intercept]' = stats.intercept,
  'RRecSnd' = stats.rrecsnd,
  'RSndSnd' = stats.rsndsnd
)

# Fit the first REM model
model1 <- FitEventNetworkCore(data, stats1)
summary(model1)

```


```{r}

# Model 2 -----------------------------------------------------------------

data <- data.frame(sid = df_high2105$sender_id, rid = df_high2105$receiver_id, time = df_high2105$event_order, sender_dialog = df_high2105$sender_dialog)

# Adding the second term: the Normalized Total Degree Received (NTDRec)
stats.ntdegrec <- NTDRec(data)
stats2 <- combine.stats(
  '[Intercept]' <- stats.intercept,
  'RRecSnd' = stats.rrecsnd,
  'RSndSnd' = stats.rsndsnd,
  'NTDegRec' = stats.ntdegrec
)

# Run the second model and check the transript_data
model2 <- FitEventNetworkCore(data, stats2, ordinal = FALSE)
summary(model2)
```


```{r}

# add a column representing if the sender and receiver are of the same gender
same_gender <- ifelse(df_high2105$sender_gender == df_high2105$receiver_gender, 1, 0)
data <- data.frame(sid = df_high2105$sender_id, rid = df_high2105$receiver_id, time = df_high2105$event_order, sender_dialog = df_high2105$sender_dialog)

# Model 3 -----------------------------------------------------------------

stats.sameGender <- SameConstGroup(data, same_gender)

stats3 <- combine.stats(
  '[Intercept]' = stats.intercept,
  'RRecSnd' = stats.rrecsnd,
  'RSndSnd' = stats.rsndsnd,
  'NTDegRec' = stats.ntdegrec,
  'SameGender' = stats.sameGender
)

# Run the third model and check the transript_data
model3 <- FitEventNetworkCore(data, stats3, ordinal = FALSE)
summary(model3)
```
```{r}

# Model 4 -----------------------------------------------------------------
#same_gender and sender_dialog
data <- data.frame(sid = df_high2105$sender_id, rid = df_high2105$receiver_id, time = df_high2105$event_order, sender_dialog = df_high2105$sender_dialog)

stats.SndDialog <- SameConstGroup(data, df_high2105$sender_dialog)
stats.RecDialog <- SameConstGroup(data, df_high2105$receiver_dialog)

stats4 <- combine.stats(
  '[Intercept]' = stats.intercept,
  'RRecSnd' = stats.rrecsnd,
  'RSndSnd' = stats.rsndsnd,
  'NTDegRec' = stats.ntdegrec,
  'SameGender' = stats.sameGender,
  'SndDialog' = stats.SndDialog,
  'RecDialog' = stats.RecDialog
)


model4 <- FitEventNetworkCore(data, stats4, ordinal = FALSE)
summary(model4)

```

