```{r, message=FALSE, warning=FALSE}
# Last Updated: 02/12
rm(list = ls())

# Load libraries
library(tidyverse)
library(tidyr)
library(lubridate)
library(ggplot2)
library(dplyr)
library(igraph)
library(readxl)
library(igraph)
library(glmnet)
library(remsonic)
# Set Path
setwd("~/RProjects/SNA_REM/REM_new/")
```

```{r}
high <- readRDS("data/high_final.RData")
low <- readRDS("data/low_perf_all.RData")
names(high)
```

# REM
All potential
RRecSndR, RSndSnd, NTDRec, SameGender, SenderGender, senderDialogueAct

1. Model 1: RRecSnd and RRecSnd
2. Model 2: RRecSnd, RSndSnd, and NTDRec
3. Model 3: RRecSnd, RSndSnd, SameGender (SenderGender)
4. Model 4: RRecSnd, RSndSnd, SndDialog



```{r}
# start timer
start_time <- Sys.time()
# add a column representing if the sender and receiver are of the same gender
samegender <- ifelse(high$sender_genderMale == high$receiver_genderMale, 1, 0)
# reove all verything that gender is not a number
samegender <- samegender[!is.na(samegender)]
high <- cbind(high, samegender)
sender_gender <- high[,5:6]
receiver_gender <- high[,7:8]
dialogue <- high[,9:14]
evtdata <- high[, 3:15]
# remove all NA in evtdata
evtdata <- evtdata[complete.cases(evtdata),]
#onvert order to time
evtdata$time <- as.POSIXct(evtdata$event_order)
evtdata <- evtdata %>% mutate(sender_id = as.factor(sender_id), receiver_id = as.factor(receiver_id))
data <- data.frame(sid = evtdata$sender_id,rid = evtdata$receiver_id,time=evtdata$time)
# Set the first moment as zero and readjust the timeline
data$time <- data$time - min(data$time)

data <- data |>
  group_by(time) |>
  mutate(time2 = row_number() - 1) |>
  ungroup() |>
  mutate(time = paste0(time, time2) |> as.numeric()) |>
  select(-time2) |>
  ungroup() |>
  as.data.frame()

# Calculate statistics for the REM
stats.intercept <- Constant(data)
stats.rrecsnd <- RRecSnd(data)
stats.rsndsnd <- RSndSnd(data)

# Combine statistics
stats1 <- combine.stats(
  '[Intercept]' = stats.intercept,
  'RRecSnd' = stats.rrecsnd,
  'RSndSnd' = stats.rsndsnd
)


end <- FALSE
start_time <- Sys.time()
# Fit the first REM model
model1 <- FitEventNetworkCore(data, stats1, ordinal = FALSE)
end <- TRUE
summary(model1)

```


```{r}
end_time <- Sys.time()
time_taken <- end_time - start_time
time_taken
```

```{r}
```





```{r}

# Model 2 -----------------------------------------------------------------

# Adding the second term: the Normalized Total Degree Received (NTDRec)
stats.ntdegrec <- NTDRec(data)
stats2 <- combine.stats(
  '[Intercept]' <- stats.intercept,
  'RRecSnd' = stats.rrecsnd,
  'RSndSnd' = stats.rsndsnd,
  'NTDegRec' = stats.ntdegrec
)


model2 <- FitEventNetworkCore(data, stats2, ordinal = FALSE)
summary(model2)
```

```{r}


# Model 3 -----------------------------------------------------------------
stats.snddialog <- SameConstGroup(data)

stats.sameconstgroup.sendergender <- SameConstGroup(data, sender_gender)
stats.sameconstgroup.receivergender <- SameConstGroup(data, receiver_gender)
stats3 <- combine.stats(
  '[Intercept]' = stats.intercept,
  'RRecSnd' = stats.rrecsnd,
  'RSndSnd' = stats.rsndsnd,
  'NTDegRec' = stats.ntdegrec,
  'SameGender' = samegender,
  'SenderDialog' = stats.snddialog,
  'SemderGender' = stats.sameconstgroup.sendergender,
  'ReceiverGender' = stats.sameconstgroup.receivergender
)
# Run the third model and check the transript_data
model3 <- FitEventNetworkCore(data, stats3, ordinal = FALSE)
summary(model3)
```

```{r}

# Model 4 -----------------------------------------------------------------
#same_gender and sender_dialog

stats.SndDialog <- SameConstGroup(data, high_perf_all$sender_dialog)

print(stats.SndDialog)
print(stats.RecDialog)
stats4 <- combine.stats(
  '[Intercept]' = stats.intercept,
  'RRecSnd' = stats.rrecsnd,
  'RSndSnd' = stats.rsndsnd,
  'NTDegRec' = stats.ntdegrec,
  'SameGender' = stats.sameGender,
  'SndDialog' = stats.SndDialog
)


model4 <- FitEventNetworkCore(data, stats4, ordinal = FALSE)
```

