---
title: "Low Performance Session (2103)"
output:
pdf_document: default
html_document: default
---
```{r, message = FALSE, include = FALSE}
# Last Updated: 02/12
rm(list = ls())

# Load libraries
library(rstudioapi)
library(tidyverse)
library(tidyr)
library(ggplot2)
library(dplyr)

library(RColorBrewer)
library(dplyr)
library(igraph)
library(readxl)
library(igraph)
library(glmnet)
library(remsonic)
library(skimr)
library(dplyr)
library(relevent)
# Install fastDummies if you haven't already
if (!requireNamespace("fastDummies", quietly = TRUE)) {
  install.packages("fastDummies")
}

library(fastDummies)

# Set Path
setwd("~/RProjects/SNA_REM/REM_new/")
```

# Session 2103
```{r}
# read excel
dialog_data <- read_excel("data/nek21.xlsx", sheet = "Sheet1_Dialogs")
# renove all dialogue act type with decision point

dialog_data <- dialog_data[dialog_data$sender_dialog != "decision_point",]
# remove all gender Unspecified
dialog_data <- dialog_data[dialog_data$sender_gender != "Unspecified",]
dialog_data <- dialog_data[dialog_data$receiver_gender != "Unspecified",]
# remove receiver_dialog
head(dialog_data)
# convert male and female as factor
dialog_data$sender_gender <- as.factor(dialog_data$sender_gender)
dialog_data$receiver_gender <- as.factor(dialog_data$receiver_gender)
dialog_data$sender_dialog <- as.factor(dialog_data$sender_dialog)

dialog_data_dummified <- dialog_data %>%
    dummy_cols(select_columns = c("sender_gender", "receiver_gender"), remove_selected_columns = TRUE)

dialog_data_dummified <- dialog_data_dummified %>%
  dummy_cols(select_columns = "sender_dialog", remove_selected_columns = TRUE)
people_list <- unique(dialog_data_dummified$sender)

lookup_table <- setNames(seq_along(people_list), people_list)
print(lookup_table)

dialog_data_dummified[, 'sender_id'] <- lookup_table[dialog_data_dummified$sender]
dialog_data_dummified[, 'receiver_id'] <- lookup_table[dialog_data_dummified$receiver]

dialog_final <- dialog_data_dummified %>% select(-c(sender, receiver, receiver_dialog)) %>% select(session, event_order, sender_id, receiver_id, everything())

head(dialog_final)
saveRDS(dialog_final, "data/dialog_final.RData")
```


# Low Session

```{r}
df_low2103 <- dialog_data[dialog_data$session == 2103,]
head(df_low2103)
# remove receiver dialogue
df_low2103 <- df_low2103[!is.na(df_low2103$receiver),]
```

```{r}



```

```{r}



```
```{r}
# session 2103
final_df <- df_low2103 %>% select(-c(sender, receiver, session))
```




```{r}
# Load the data
data <- data.frame(sid = df_low2103$sender_id, rid = df_low2103$receiver_id, time = df_low2103$event_order)


# Calculate statistics for the REM
stats.intercept <- Constant(data)
stats.rrecsnd <- RRecSnd(data)
stats.rsndsnd <- RSndSnd(data)

# Combine statistics
stats1 <- combine.stats(
  '[Intercept]' = stats.intercept,
  'RRecSnd' = stats.rrecsnd,
  'RSndSnd' = stats.rsndsnd
)

# Fit the first REM model
model1 <- FitEventNetworkCore(data, stats1)
summary(model1)

```


```{r}

# Model 2 -----------------------------------------------------------------

data <- data.frame(sid = df_low2103$sender_id, rid = df_low2103$receiver_id, time = df_low2103$event_order, sender_dialog = df_low2103$sender_dialog_statement, 

# Adding the second term: the Normalized Total Degree Received (NTDRec)
stats.ntdegrec <- NTDRec(data)
stats2 <- combine.stats(
  '[Intercept]' <- stats.intercept,
  'RRecSnd' = stats.rrecsnd,
  'RSndSnd' = stats.rsndsnd,
  'NTDegRec' = stats.ntdegrec
)

# Run the second model and check the transript_data
model2 <- FitEventNetworkCore(data, stats2, ordinal = FALSE)
summary(model2)
```


```{r}

# add a column representing if the sender and receiver are of the same gender
same_gender <- ifelse(df_low2103$sender_gender == df_low2103$receiver_gender, 1, 0)
# factor

data <- data.frame(sid = df_low2103$sender_id, rid = df_low2103$receiver_id, time = df_low2103$event_order, sender_dialog = df_low2103$sender_dialog)

# Model 3 -----------------------------------------------------------------

stats.sameGender <- SameConstGroup(data, same_gender)

stats3 <- combine.stats(
  '[Intercept]' = stats.intercept,
  'RRecSnd' = stats.rrecsnd,
  'RSndSnd' = stats.rsndsnd,
  'NTDegRec' = stats.ntdegrec,
  'SameGender' = stats.sameGender
)

# Run the third model and check the transript_data
model3 <- FitEventNetworkCore(data, stats3, ordinal = FALSE)
summary(model3)
```

```{r}

# Model 4 -----------------------------------------------------------------
#same_gender and sender_dialog
data <- data.frame(sid = df_low2103$sender_id, rid = df_low2103$receiver_id, time = df_low2103$event_order, sender_dialog = df_low2103$sender_dialog)


stats.SndDialog <- SameConstGroup(data, df_low2103$sender_dialog)
stats.RecDialog <- SameConstGroup(data, df_low2103$receiver_dialog)

print(stats.SndDialog)
print(stats.RecDialog)
stats4 <- combine.stats(
  '[Intercept]' = stats.intercept,
  'RRecSnd' = stats.rrecsnd,
  'RSndSnd' = stats.rsndsnd,
  'NTDegRec' = stats.ntdegrec,
  'SameGender' = stats.sameGender,
  'SndDialog' = stats.SndDialog,
  'RecDialog' = stats.RecDialog
)


model4 <- FitEventNetworkCore(data, stats4, ordinal = FALSE)
summary(model4)

```

