---
output:
  pdf_document: default
  html_document: default
---
```{r,include=FALSE}
# Last Updated: 02/12
rm(list = ls())

# Load libraries
library(tidyverse)
library(tidyr)
library(ggplot2)
library(dplyr)
library(igraph)
library(glmnet)
library(skimr)
library(dplyr)
library(relevent)
library(sna)
library(skimr)
library(dplyr)
library(relevent)
library(tidyr)
conflicted::conflict_prefer("select", "dplyr")
conflicted::conflict_prefer("filter", "dplyr") 
gradient <- viridis::mako(8)
# start with lighter color
gradient <- gradient[8:3]

knitr::opts_chunk$set(
    echo = TRUE,
    message = FALSE,
    warning = FALSE,
    tidy = TRUE,
    dpi = 800,
    hide = TRUE
    )
setwd("~/RProjects/SNA_REM/REM_new/")
```


```{r,echo=FALSE, include=FALSE,eval=FALSE}
high_perf_sessions <- readRDS("data/high_final.RData") %>% rename(dialog = sender_dialog)
high_perf_sessions %>% saveRDS("data/high_performance_sessions.RData")
high_perf_sessions %>% write.csv("data/high_performance_sessions.csv")

low_perf_sessions <- readRDS("data/low_final.RData") %>% rename(dialog = sender_dialog)
low_perf_sessions %>% saveRDS("data/low_performance_sessions.RData")
low_perf_sessions %>% write.csv("data/low_performance_sessions.csv")
```

Igor Ashley   Will  Katya  Saleh   Oleg   Vika   Alex 
 1      2      3      4      5      6      7      8 

```{r}
interactions_high <- readRDS("data/low_performance_sessions.RData")
unique(interactions_high$session)
unique(interactions_high$sender_id)
```



```{r}
size <- nrow(interactions_high)
```


```{r}
# Create a dataframe with names
attribute_table <- data.frame(
  id = 0:8,
  name = c("All", "Igor", "Ashley", "Will", "Katya", "Saleh", "Oleg", "Vika", "Alex"),
  stringsAsFactors = FALSE
)
attribute_table <- na.omit(attribute_table)
attribute_table$Sender_male <- ifelse(attribute_table$name %in% c("Igor", "Will", "Saleh", "Oleg", "Alex"), 1,
                                 ifelse(attribute_table$name %in% c("Ashley", "Katya", "Vika"), 0, NA)) 
attribute_table$Receiver_male <- ifelse(attribute_table$name %in% c("Igor", "Will", "Saleh", "Oleg", "Alex"), 1,
                                 ifelse(attribute_table$name %in% c("Ashley", "Katya", "Vika"), 0, NA)) 

attributes <- attribute_table %>% dplyr::select(-name)

head(attributes)
```




```{r}


interactions_high <- interactions_high[interactions_high$session%in% c(2102,2106, 2107, 2110),] %>% select(time, sender_id, receiver_id,dialog)
head(interactions_high)


attributes <- attributes[attributes$id %in% interactions_high$sender_id,]

dim(interactions_high)

size <- nrow(attributes)

head(attributes)
```

 
 
# Model 1 Baseline Model
```{r}

edgelist_high <-interactions_high[, c("time", "sender_id", "receiver_id")]
# Assuming 'dataframe' is your dataframe and 'time' is the column name
attributes$intercept <- 1
r <- nrow(interactions_high)
edgelist_high <- rbind(edgelist_high, c(r + 1, NA, NA))
set.seed(1000) 

```


```{r,warning=FALSE}

mod1 <- rem.dyad(edgelist = edgelist_high, n = size, 
                 effects = c("CovSnd"), 
                 covar = list(CovSnd = attributes$intercept), 
                 ordinal = TRUE, hessian = TRUE)
```


```{r}
summary(mod1)
```


# Model 2
```{r}



CovSnd1 <- cbind(attributes[, c("intercept", "Sender_male")])


mod2 <- rem.dyad(edgelist_high, n = size, 
                  effects = c("CovSnd"), 
                  covar = list(CovSnd = CovSnd1), 
                  ordinal = TRUE, hessian = TRUE)

```
```{r}
summary(mod2)
```


```{r}
coef_names2 <- c("Intercept", "Sender_male")
names(mod2$coef) <- coef_names2
summary(mod2)


```

```{r}
inputs <- c(intercept = 1, Sender_male = 1)
hazard_male_send <- exp(sum(mod2$coef * inputs))
cat(-hazard_male_send)
```


# Model 3
```{r}

CovSnd <- cbind(attributes[, c("intercept", "Sender_male")])

CovRec <- cbind(attributes[, c("Receiver_male")])

mod3 <- rem.dyad(edgelist_high, n = size, 
                  effects = c("CovSnd","CovRec"), 
                  covar = list(CovSnd = CovSnd, CovRec = CovRec), 
                  ordinal = TRUE, hessian = TRUE)

coef_names3 <- c("Intercept", "Sender_male", "Receiver_male")
names(mod3$coef) <- coef_names3

summary(mod3)
```
