---
title: "REM for Low Performing Sessions"
output:
  html_document:
    toc: false
    toc_depth: '4'
    df_print: paged
  pdf_document:
    toc: false
    toc_depth: 4
    number_sections: false
    fig_caption: true
    keep_tex: true
    latex_engine: xelatex
editor_options: null
y  markdown:
  wrap: 72
---

```{r setup, include=FALSE}

rm(list=ls())

library(caret)
library(network)
library(relevent)
library(survival)
library(rem)
library(dplyr)
library(ggplot2)
library(igraph)
library(ggraph)
library(RColorBrewer)
library(tidyr)
setwd("~/RProjects/SNA_REM/REM_new")
knitr::opts_chunk$set(fig.align='center', fig.width=8, fig.height=6, options(tidy = TRUE), tidy.opts = list(width.cutoff = 60))

```


```{r}
# Interactions Data Frame (Edges)
low_perf_interactions <- readRDS("data/low_performance_sessions.RData") %>% filter(session != 2102) %>%
  select(session, sender_id, receiver_id, dialog, time)


interactions <- low_perf_interactions %>%
  mutate(
    sender_id = as.integer(sender_id),  
    receiver_id = as.integer(receiver_id), 
    dialog = as.factor(dialog) 
  )



actors_attributes <- data.frame(
  id = 1:6,
  name = c("Igor", "Ashley", "Will", "Saleh", "Oleg", "Vika"),
  gender = c("male", "female", "male", "male", "male", "female")
)

# Create dummy variables for gender
dummyvars <- dummyVars(" ~ gender", data = actors_attributes)
actors_attributes <- cbind(actors_attributes, predict(dummyvars, actors_attributes)) %>%
  select(id, name, gendermale)
```



## Summary by Session and Speaker

```{r,eval=FALSE}
session_dialogues <- low_perf_interactions %>%
  group_by(session) %>%
  summarise(n = n())


ggplot(session_dialogues, aes(x = factor(session), y = n, fill = factor(session))) + 
  geom_bar(stat = "identity") +
  scale_fill_brewer(palette = "Pastel1") +  
  labs(title = "Number of Dialogues Per Session (Low Performance)",
       x = "Session",
       y = "Number of Dialogues",
       fill = "Session") +
  theme_minimal() +  
  # text size
  theme(axis.text.x = element_text(size = 11, angle = 45, hjust = 0.5)) +
  theme(legend.position = "none") 

```



```{r}
low_perf_interactions %>% filter (sender_id %in% actors_attributes$id) %>% filter(receiver_id %in% actors_attributes$id) ->low_perf_interactions

unique(low_perf_interactions$sender_id)

```


```{r, eval=FALSE}
dialogues_per_speaker_session <- low_perf_interactions %>%
  left_join(actors_attributes, by = c("sender_id" = "id")) %>%
  group_by(session, name) %>%
  summarise(number_of_dialogues = n(), .groups = 'drop') %>%
  arrange(session, desc(number_of_dialogues))

dialogues_summary_tibble <- as_tibble(dialogues_per_speaker_session)
dialogues_summary_tibble
```


```{r, eval=FALSE}
ggplot(dialogues_summary_tibble, aes(x = name, y = number_of_dialogues, fill = name)) + 
  geom_bar(stat = "identity") +
  facet_wrap(~session) +
  scale_fill_brewer(palette = "Pastel1") +  
  labs(subtitle = "Number of Dialogues Per Speaker Per Session (Low Performance)",
       x = "Speaker",
       y = "Number of Dialogues",
       fill = "Speaker") +
  theme_minimal() + 
  theme(strip.text.x = element_text(size = 9), strip.text.y = element_text(size = 12)) +
  # text size
  theme(axis.text.x = element_text(size = 8, angle = 45, hjust = 1)) +
  theme(legend.position = "none") 

```

```{r}
actors_attributes <- data.frame(
  id = 1:6,
  name = c("Igor", "Ashley", "Will", "Saleh", "Oleg", "Vika"),
  gender = c("male", "female", "male", "male", "male", "female")
)

total_dialogues_per_speaker <- low_perf_interactions %>%
  left_join(actors_attributes, by = c("sender_id" = "id")) %>%
  group_by(name) %>%
  summarise(number_of_dialogues = n(), .groups = 'drop') %>%
  arrange(desc(number_of_dialogues)) %>%  as_tibble() 
total_dialogues_per_speaker %>% print()
```


```{r, eval=FALSE}
ggplot(total_dialogues_per_speaker, aes(x = name, y = number_of_dialogues, fill = name)) + 
  geom_bar(stat = "identity") +
  scale_fill_brewer(palette = "Pastel1") +  
  labs(subtitle = "Number of Dialogues Across All Sections By Speaker (Low Performance)",
       x = "Speaker",
       y = "Number of Dialogues",
       fill = "Speaker") +
  theme_minimal() + 
  theme(legend.position = "none") 
```


```{r}

low_perf_interactions %>% filter(receiver_id != 0)  %>% select(-session) %>% mutate(time = 1:nrow(.))  %>% select(sender_id, receiver_id, time,dialog)  %>% mutate(dialog = as.factor(dialog), sender_id = as.integer(sender_id), receiver_id = as.integer(receiver_id)) -> interactions

actors_attributes %>% filter(id %in% interactions$sender_id) %>% filter(id %in% interactions$receiver_id) -> actors_attributes
head(actors_attributes)


g_subset <- graph_from_data_frame(interactions, directed = TRUE, vertices = data.frame(actors_attributes))
```


```{r, eval=FALSE}
V(g_subset)$gender <- actors_attributes$gender[match(V(g_subset)$name, actors_attributes$name)]
V(g_subset)$name <- actors_attributes$name[match(V(g_subset)$name, actors_attributes$name)]
ggraph(g_subset, layout = 'fr') +
  geom_edge_link(aes(color = dialog), alpha = 0.7, edge_width = .2, lineend = "butt", arrow = arrow(type = 'closed', length = unit(4, 'mm'))) +
  scale_edge_color_manual(values = dialog_color_map) +
  geom_node_point(aes(color = factor(gender)), size = 4, alpha = 0.8) +
  geom_node_text(aes(label = name), repel = TRUE,  color = "black", size = 3, vjust = 1, nudge_x = -.02) +
  scale_color_manual(values = c('0' = 'red', '1' = 'cyan')) +
  theme_void() +
  labs(subtitle = "Low Performing Session", color = "Gender", edge_color = "Dialog") +
  theme(legend.position = "right", legend.title = element_text(size = 8))
```

```{r}
# remove alex from sender_id
actors_attributes %>% filter(name != "Alex") -> actors_attributes

low_perf_interactions %>% filter(receiver_id != 0) %>% select(-session) %>% mutate(time = 1:nrow(.))  %>% select(sender_id, receiver_id, time,dialog)  %>% mutate(dialog = as.factor(dialog), sender_id = as.integer(sender_id), receiver_id = as.integer(receiver_id)) -> interactions

actors_attributes %>% filter(id %in% interactions$sender_id) %>% filter(id %in% interactions$receiver_id) -> actors_attributes
head(actors_attributes)
dim(low_perf_interactions)
unique(low_perf_interactions$session)

```


```{r}
low_perf_interactions <- low_perf_interactions %>% filter(receiver_id != 0) %>% select(-session) %>% mutate(time = 1:nrow(.)) %>% select(sender_id, receiver_id, time,dialog)  %>% mutate(dialog = as.factor(dialog), sender_id = as.integer(sender_id), receiver_id = as.integer(receiver_id)) %>% filter(sender_id %in% actors_attributes$id) %>% filter(receiver_id %in% actors_attributes$id)
```



```{r}
actors_attributes %>% filter(id %in% interactions$sender_id) %>% filter(id %in% interactions$receiver_id) -> actors_attributes

g_subset <- graph_from_data_frame(interactions, directed = TRUE, vertices = data.frame(actors_attributes))

V(g_subset)$gender <- actors_attributes$gender[match(V(g_subset)$name, actors_attributes$name)]
V(g_subset)$name <- actors_attributes$name[match(V(g_subset)$name, actors_attributes$name)]

```



```{r, eval=FALSE}
interactions$time<-as.numeric(interactions$time) 


REM.data <- createRemDataset(
  data = interactions, 
  sender = interactions$sender_id,
  target = interactions$receiver_id,
  eventSequence = interactions$time,
  eventAttribute = interactions$dialog,
  atEventTimesOnly = TRUE, 
  untilEventOccurrs = TRUE,
  includeAllPossibleEvents = FALSE, 
  returnInputData = FALSE
)

#save as RDS
saveRDS(REM.data, "data/RemDatasetLow.RDS")

```

```{r, eval=TRUE}
readRDS("data/RemDatasetLow.RDS") -> REM.data
```



```{r}
dim(REM.data)
```

```{r}
str(REM.data)
```

```{r}
surv_object <- Surv(time = REM.data$eventTime, event = REM.data$eventDummy)
```


```{r}
base_model <- coxph(surv_object ~ 1, data = REM.data)
summary(base_model)
```



```{r}
sender_model <- coxph(surv_object ~ sender + 1, data = REM.data)


summary(sender_model)

```


```{r}
rec_model <- coxph(surv_object ~ target + 1, data = REM.data)


summary(rec_model)


```
```{r}
snd_rec_model <- coxph(surv_object ~ sender + target + 1, data = REM.data)
summary(snd_rec_model)


```

```{r}

event_model <- coxph(surv_object ~ eventAttribute + 1, data = REM.data)
summary(event_model)
```

```{r}
model4 <- coxph(surv_object ~ sender + eventAttribute, data = REM.data)
summary(model4)
```

# INCREASE ITER

```{r}
model5 <- coxph(surv_object ~ sender * eventAttribute, data = REM.data)
summary(model5)
```



