---
output:
  pdf_document: default
  html_document: default
---
```{r, message = FALSE, include = FALSE}
# Last Updated: 02/12
rm(list = ls())

# Load libraries
library(rstudioapi)
library(tidyverse)
library(tidyr)
library(ggplot2)
library(dplyr)

library(RColorBrewer)
library(dplyr)
library(igraph)
library(readxl)
library(igraph)
library(glmnet)
library(remsonic)
library(skimr)
library(dplyr)
library(relevent)
# Set Path
setwd("~/RProjects/SNA_REM/REM_new/")
```


```{r}
readRDS("data/rem_data.rds") -> data
data %>% filter(!is.na(snd_da) & !is.na(rec_da)) %>% glimpse()
# rename
# rename all the columns
colnames(data) <- c("session", "sid", "rid", "sgend"er, "rgender", "sdialog", "rdialog", "event_order", "event_time")
```

```{r}
```
```{r}
head(data)
```
```{r}
# set 0 if snd_gender == Female and 0 if snd_gender = Male
data$snd_gender <- ifelse(data$snd_gender== "Female", 0, 1)
data$rec_gender <- ifelse(data$rec_gender== "Female", 0, 1)


data$snd_id <- as.factor(data$snd_id)
data$rec_id <- as.factor(data$rec_id)
data$snd_gender <- as.factor(data$snd_gender)
data$rec_gender <- as.factor(data$rec_gender)
data$sdialog <- as.factor(data$snd_da)
data$rdialog <- as.factor(data$rec_da)
head(data)
```







```{r}


df_2103$session <- NULL
# row names
df_2103 <- df_2103 %>%  mutate(event_order = row_number())
# drop the first column
head(df_2103)
```

# Session 2103




```{r}


data <- data.frame(sid = df_2103$snd_id, rid = df_2103$rec_id, time = df_2103$event_order)



# Model 1 -----------------------------------------------------------------

# Calculate the first set of statistics: the intercept, the effects for repetition (RSndSnd), 
# and reciprocity (RRecSnd)

stats.intercept <- Constant(data)
stats.rrecsnd <- RRecSnd(data)
stats.rsndsnd <- RSndSnd(data)


stats1 <- combine.stats(
  '[Intercept]' = stats.intercept,
  'RRecSnd' = stats.rrecsnd,
  'RSndSnd' = stats.rsndsnd
)

model1 <- FitEventNetworkCore(data, stats1)
summary(model1)
```


```{r}
# Model 2 -----------------------------------------------------------------

# Adding the second term: the Normalized Total Degree Received (NTDRec)
stats.ntdegrec <- NTDRec(data)
stats2 <- combine.stats(
  '[Intercept]' <- stats.intercept,
  'RRecSnd' = stats.rrecsnd,
  'RSndSnd' = stats.rsndsnd,
  'NTDegRec' = stats.ntdegrec
)

# Run the second model and check the transript_data
model2 <- FitEventNetworkCore(data, stats2, ordinal = FALSE)
summary(model2)
```


```{r}
# Model 3 -----------------------------------------------------------------
stats.sameconstgroup.da <- SameConstGroup(data, snd_gender, rec_gender)

stats3 <- combine.stats(
  '[Intercept]' = stats.intercept,
  'RRecSnd' = stats.rrecsnd,
  'RSndSnd' = stats.rsndsnd,
  'NTDegRec' = stats.ntdegrec,
  'SameConstGroup' = stats.sameconstgroup.da
)

# Run the third model and check the transript_data
model3 <- FitEventNetworkCore(data, stats3, ordinal = FALSE)
summary(model3)
```



