```{r, message=FALSE, warning=FALSE}
# Last Updated: 03.01
rm(list = ls())

library(tidyverse)
library(tidyr)
library(lubridate)
library(dplyr)
library(igraph)
library(readxl)
library(glmnet)


library(relevent)
setwd("~/RProjects/SNA_REM/REM_new/")
```

```{r}

high <- readRDS("data/high_performance_sessions.RData")
# retain al those gender is Unspecified

low <- readRDS("data/low_perf_final.RData")
names(high)
```

# REM
All potential
RRecSndR, RSndSnd, NTDRec, SameGender, SenderGender, senderDialogueAct

1. Model 1: RRecSnd and RRecSnd
2. Model 2: RRecSnd, RSndSnd, and NTDRec
3. Model 3: RRecSnd, RSndSnd, SameGender (SenderGender)
4. Model 4: RRecSnd, RSndSnd, SndDialog

```{r}
high2103 <- high %>% filter(session == "2103") 
low2106 <- low %>% filter(session == "2106") 
```


```{r}
high <- high2103
# Model 1 -----------------------------------------------------------------
# complete cases
samegender <- (high[, 6] == high[, 8]) | (high[, 7] == high[, 9])
high <- cbind(high, samegender)
high <- high[complete.cases(high),]

sender_gender <- high[,6:7]
receiver_gender <- high[,8:9]
dialogue <- high[,10:14]
evtdata <- high[, c(2, 3:14)] %>% rename("timestamp" = "in_session_event_order") %>% as.data.frame()
names(evtdata)
```


```{r}
library(lubridate)
evtdata$timestamp <- as.POSIXct(evtdata$timestamp, origin = "1970-01-01")
# remove - 
evtdata$timestamp <- as.numeric(evtdata$timestamp)
data <- evtdata %>% select(sender_id, receiver_id, timestamp) %>%as.matrix()
# Calculate statistics for thde REM
stats.intercept <- Constant(data)
stats.rrecsnd <- RRecSnd(data)
stats.rsndsnd <- RSndSnd(data)

rem_fit <- rem(eventlist = data, statslist = c(stats.intercept, stats.rrecsnd, stats.rsndsnd))

summary(rem_fit)
```





```{r}

# Model 2 -----------------------------------------------------------------

# Adding the second term: the Normalized Total Degree Received (NTDRec)
stats.ntdegrec <- NTDRec(data)
stats2 <- combine.stats(
  '[Intercept]' <- stats.intercept,
  'RRecSnd' = stats.rrecsnd,
  'RSndSnd' = stats.rsndsnd,
  'NTDegRec' = stats.ntdegrec
)


model2 <- FitEventNetworkCore(data, stats2, ordinal = FALSE)
summary(model2)
```

```{r}


# Model 3 -----------------------------------------------------------------
stats.snddialog <- SameConstGroup(data)

stats.sameconstgroup.sendergender <- SameConstGroup(data, sender_gender)
stats.sameconstgroup.receivergender <- SameConstGroup(data, receiver_gender)
stats3 <- combine.stats(
  '[Intercept]' = stats.intercept,
  'RRecSnd' = stats.rrecsnd,
  'RSndSnd' = stats.rsndsnd,
  'NTDegRec' = stats.ntdegrec,
  'SameGender' = samegender,
  'SenderDialog' = stats.snddialog,
  'SemderGender' = stats.sameconstgroup.sendergender,
  'ReceiverGender' = stats.sameconstgroup.receivergender
)
# Run the third model and check the transript_data
model3 <- FitEventNetworkCore(data, stats3, ordinal = FALSE)
summary(model3)
```

```{r}

# Model 4 -----------------------------------------------------------------
#same_gender and sender_dialog

stats.SndDialog <- SameConstGroup(data, high_perf_all$sender_dialog)

print(stats.SndDialog)
print(stats.RecDialog)
stats4 <- combine.stats(
  '[Intercept]' = stats.intercept,
  'RRecSnd' = stats.rrecsnd,
  'RSndSnd' = stats.rsndsnd,
  'NTDegRec' = stats.ntdegrec,
  'SameGender' = stats.sameGender,
  'SndDialog' = stats.SndDialog
)


model4 <- FitEventNetworkCore(data, stats4, ordinal = FALSE)
```

